---
- name: Remove nginx on CentOS
  hosts: CentOS
  gather_facts: no
  become: yes

  tasks:
    - name: install epel-release
      yum: name=epel-release state=absent
    - nmae: install nginx web server
      yum: name=nginx state=absent